var GetRandomResponse = function(){
	var leng = PetResponses.length;
	var index = Math.floor(Math.random()*leng);
	return myPetsTabPet.name + PetResponses[index];
};

var PetResponses = new Array(
	" looks quizically at you...",
	" starts hopping around!",
	" smiles slyly.",
	" looks suspiciously at you..",
	" runs around really fast.",
	" looks shocked!",
	" is not sure what to say..",
	" looks hungry. Uh...",
	" turns away dramatically!",
	" whispers a secret in your ear!",
	" stares blankly back.",
	" considers what you said..",
	" doesn't reply.",
	" yawns in response.",
	" doesn't like the tone of your voice!",
	" smiles eagerly!",
	" paws at you playfully.",
	" puts their paw on your shoulder and looks worried.",
	" looks proud!",
	" electric shocks you!",
	" regrets what has been done...",
	" seems to beckon for you.",
	" stares at you ominously.",
	" whistles a cute tune!",
	" teaches you a trick!",
	" tells you you're their favorite!",
	" wonders what you're thinking about...",
	" cannot possibly consider that!",
	" spins in a circle!",
	" doesn't wish to reply at this time",
	" looks wistfully out the window.",
	" shouts at the top of their lungs!",
	" rolls over.",
	" just sits there and looks cute.",
	" contemplates life.",
	" wags their tail!",
	" whimpers in response.",
	" rolls their eyes.",
	" frowns thoughtfully.",
	" giggles at what you said!",
	" laughs heartily!",
	" understands what you mean.",
	" replies insightfully.",
	" copies what you said!",
	" looks like they want to be petted!",
	" agrees wholeheartedly!",
	" disagrees somewhat..."
);